### ISSUE TITLE
Color overlays break with greyscale images

### ISSUE THREAD

**Issue by TimNagle-McNaughton** [gmorinan/click2label#1]
Cool project! Really like the idea.

While running 100x100 greyscale png's, the color overlays broke. I added cmap="grey" to the try statement in update which displays the images correctly, but the color overlays turn into a checkerboard of two colors. Changing the colors to "black"/"k" produced a solid output, although one that is purple. 

I tracked the issue to np.resize. It only fills every other value of the first channel (the only one overlayed) with the a value because it thinks the image has three channels when in reality it doesn't (img.shape returns (width, height) only for greyscale).

This problem can be fixed by changing:

`self.ax.imshow(np.resize(mpcolors.to_rgb(overlay), self.image.shape), alpha=0.4)`

to something like
`width, height = self.image.shape`
`self.ax.imshow(np.resize(mpcolors.to_rgb(overlay), (width, height, 3), alpha=0.4))`

**Comment by gmorinan** [comment]
Thanks for comment! I have made this fix. All the best

**Comment by TimNagle-McNaughton** [comment]
Awesome. Used this project for some research, should find yourself in the acknowledgments of the manuscript eventually!

**Comment by gmorinan** [comment]
Glad it helped! Feel free to cite this repo or the article I wrote about it https://towardsdatascience.com/one-mouse-click-to-label-an-image-within-a-jupyter-notebook-40053095333a
